twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        version: 'v1.0'
        cmsname: 'OvaleCMS'
        cmscolor: 'rgb(91,177,47)'
