<?php

namespace Container7wURIMe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModifPlayerTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ModifPlayerType' shared autowired service.
     *
     * @return \App\Form\ModifPlayerType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ModifPlayerType.php';

        return $container->privates['App\\Form\\ModifPlayerType'] = new \App\Form\ModifPlayerType();
    }
}
